_target_: animatableGaussian.dataset.peoplesnapshot.PeopleSnapshotDataModule
name: peoplesnapshot-male-3-casual
num_workers: ${num_workers}
gender: male
subject: male-3-casual
num_players: 1
opt:
  dataroot: ../../data/PeopleSnapshot/${dataset.subject}
  max_freq: ${max_freq}
  train:
    start: 0
    end: 455
    skip: 4
    downscale: 2
  val:
    start: 0
    end: 0
    skip: 4
    downscale: 2
  test:
    start: 456
    end: 675
    skip: 4
    downscale: 2